name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Build application
        run: make

      - name: Build test
        run: make test

      - name: Run tests
        run: make run_test
